server:
  port: 80
  max-http-header-size: 10240

guns:
  spring-session-open: false        #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800     #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900  #多久检测一次失效的session(只在单机环境下生效) 单位：秒

beetl:
  resource-auto-check: true         #热加载beetl模板，开发时候用

spring:
  profiles:
    active: @spring.active@
  mvc:
    view:
      prefix: /pages
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

mybatis-plus:
  typeAliasesPackage: cn.stylefeng.guns.modular.system.model
  mapper-locations:
    - classpath*:cn/stylefeng/guns/**/mapping/*.xml

log:
  path: _app_logs